class Power {
    data = {
        _id: "",
        name: "",
        type: "power",
        img: "icons/magic/air/wind-vortex-swirl-red.webp",
        data: {
            description: {
                value: "",
                chat: "",
                unidentified: "",
            },
            source: "",
            activation: {
                type: "",
                cost: 0,
                condition: "",
            },
            duration: {
                value: null,
                units: "",
            },
            target: "",
            range: {
                value: null,
                long: null,
                units: "",
            },
            uses: {
                value: 0,
                max: 0,
                per: "",
            },
            consume: {
                type: "",
                target: "",
                amount: null,
            },
            macro: {
                type: "script",
                scope: "global",
                launchOrder: "off",
                command: "",
                author: "",
            },
            keyWords: [""],
            level: "",
            powersource: "",
            secondPowersource: "",
            subName: "",
            prepared: true,
            powerType: "",
            useType: "atwill",
            actionType: "minor",
            requirements: "",
            weaponType: "none",
            weaponUse: "none",
            rangeType: "personal",
            rangeTextShort: "",
            rangeText: "",
            rangePower: null,
            area: 0,
            rechargeRoll: "",
            rechargeCondition: "",
            damageShare: false,
            postEffect: true,
            postSpecial: true,
            autoGenChatPowerCard: true,
            sustain: {
                actionType: "none",
                detail: "",
            },
            attack: {
                shareAttackRoll: false,
                isAttack: true,
                ability: "str",
                abilityBonus: 0,
                def: "ac",
                defBonus: 0,
                formula: "@wepAttack + @powerMod + @lvhalf + @atkMod",
                damageType: {},
                effectType: {},
            },
            hit: {
                shareDamageRoll: false,
                isDamage: false,
                isHealing: false,
                baseQuantity: "1",
                baseDiceType: "weapon",
                detail: "",
                formula: "@powBase + @powerMod + @wepDamage + @dmgMod",
                critFormula:
                    "@powMax + @powerMod + @wepDamage + @wepCritBonus + @dmgMod",
                healFormula: "",
            },
            miss: {
                detail: "",
                formula: "@damageFormula/2",
            },
            effect: {
                detail: "",
            },
            damage: {
                parts: [],
            },
            damageCrit: {
                parts: [],
            },
            damageImp: {
                parts: [],
            },
            damageCritImp: {
                parts: [],
            },
            trigger: "",
            requirement: "",
            special: "",
            specialAdd: {
                parts: [],
            },
            type: "",
            damageType: {
                damage: false,
                acid: false,
                cold: false,
                fire: false,
                force: false,
                lightning: false,
                necrotic: false,
                physical: false,
                poison: false,
                psychic: false,
                radiant: false,
                thunder: false,
            },
            effectType: {
                augmentable: false,
                aura: false,
                beast: false,
                beastForm: false,
                channelDiv: false,
                charm: false,
                conjuration: false,
                disease: false,
                elemental: false,
                enchantment: false,
                evocation: false,
                fear: false,
                fullDis: false,
                gaze: false,
                healing: false,
                illusion: false,
                invigorating: false,
                mount: false,
                necro: false,
                nether: false,
                poison: false,
                polymorph: false,
                rage: false,
                rattling: false,
                reliable: false,
                runic: false,
                sleep: false,
                spirit: false,
                stance: false,
                summoning: false,
                teleportation: false,
                transmutation: false,
                zone: false,
            },
            chatFlavor: "",
        },
        effects: [],
        folder: null,
        sort: 0,
        permission: {
            default: 0,
        },
        flags: {},
    };
}
class Feat {
    data = {
        _id: "NGFhedSbb4y3GGc6",
        name: "sample",
        type: "feat",
        img: "icons/magic/movement/chevrons-down-yellow.webp",
        data: {
            description: {
                value: "",
                chat: "",
                unidentified: "",
            },
            source: "",
            activation: {
                type: "",
                cost: 0,
                condition: "",
            },
            duration: {
                value: null,
                units: "",
            },
            target: {
                value: null,
                width: null,
                units: "",
                type: "",
            },
            range: {
                value: null,
                long: null,
                units: "",
            },
            uses: {
                value: 0,
                max: 0,
                per: null,
            },
            consume: {
                type: "",
                target: null,
                amount: null,
            },
            macro: {
                type: "script",
                scope: "global",
                launchOrder: "off",
                command: "",
                author: "",
            },
            requirements: "",
            level: "",
            recharge: {
                value: null,
                charged: false,
            },
        },
        effects: [],
        folder: null,
        sort: 0,
        permission: {
            default: 0,
            "14Edqw6IS6HfTI0G": 3,
        },
        flags: {},
    };
}
class Armour {
    data = {
        _id: "dQdLgwiiy7tTQYlo",
        name: "sample",
        type: "equipment",
        img: "icons/equipment/chest/breastplate-sculpted-blue.webp",
        data: {
            description: {
                value: "",
                chat: "",
                unidentified: "",
            },
            source: "",
            quantity: 1,
            weight: 0,
            price: 0,
            attuned: false,
            equipped: false,
            rarity: "",
            identified: true,
            activation: {
                type: "",
                cost: 0,
                condition: "",
            },
            duration: {
                value: null,
                units: "",
            },
            target: {
                value: null,
                width: null,
                units: "",
                type: "",
            },
            range: {
                value: null,
                long: null,
                units: "",
            },
            uses: {
                value: 0,
                max: 0,
                per: null,
            },
            consume: {
                type: "",
                target: null,
                amount: null,
            },
            armour: {
                value: 10,
                type: "armour",
                subType: "cloth",
                ac: 0,
                fort: 0,
                ref: 0,
                wil: 0,
                dex: null,
                movePen: false,
                movePenValue: 0,
                skillCheck: false,
                skillCheckValue: 0,
                damageRes: {
                    parts: [],
                },
            },
            hp: {
                value: 0,
                max: 0,
                dt: null,
                conditions: "",
            },
            macro: {
                type: "script",
                scope: "global",
                launchOrder: "off",
                command: "",
                author: "",
            },
            speed: {
                value: null,
                conditions: "",
            },
            strength: 0,
            stealth: false,
            proficient: true,
        },
        effects: [],
        folder: null,
        sort: 0,
        permission: {
            default: 0,
            "14Edqw6IS6HfTI0G": 3,
        },
        flags: {},
    };
}
class Weapon {
    data = {
        _id: "JnKvpp52nfe8tbif",
        name: "Blade",
        type: "weapon",
        img: "icons/weapons/swords/sword-guard-steel-green.webp",
        data: {
            description: {
                value: "",
                chat: "",
                unidentified: "",
            },
            source: "",
            quantity: 1,
            weight: 0,
            price: 0,
            attuned: true,
            equipped: true,
            rarity: "",
            identified: true,
            activation: {
                type: "",
                cost: 0,
                condition: "",
            },
            duration: {
                value: null,
                units: "",
            },
            target: {
                value: null,
                width: null,
                units: "",
                type: "",
            },
            range: {
                value: 5,
                long: 10,
                units: "",
            },
            uses: {
                value: 0,
                max: 0,
                per: "",
            },
            consume: {
                type: "",
                target: "",
                amount: null,
            },
            armour: {
                value: 10,
            },
            hp: {
                value: 0,
                max: 0,
                dt: null,
                conditions: "",
            },
            macro: {
                type: "script",
                scope: "global",
                launchOrder: "off",
                command: "",
                author: "",
            },
            weaponType: "simpleM",
            weaponHand: "hMain",
            properties: {
                amm: false,
                bru: false,
                def: false,
                hic: false,
                imp: false,
                lof: false,
                lom: false,
                off: false,
                rch: false,
                rel: false,
                sml: false,
                spc: false,
                thv: false,
                tlg: false,
                two: false,
                ver: false,
            },
            proficient: true,
            proficientI: false,
            profBonus: 0,
            profImpBonus: 0,
            enhance: 0,
            isRanged: false,
            damageDice: {
                parts: [["1", "8", ""]],
            },
            damage: {
                parts: [],
            },
            damageCrit: {
                parts: [],
            },
            damageImp: {
                parts: [],
            },
            damageCritImp: {
                parts: [],
            },
            damageType: {
                physical: true,
                damage: false,
                acid: false,
                cold: false,
                fire: false,
                force: false,
                lightning: false,
                necrotic: false,
                poison: false,
                psychic: false,
                radiant: false,
                thunder: false,
            },
            brutalNum: 1,
            weaponGroup: {
                axe: false,
                blowgun: false,
                bow: false,
                cbow: false,
                dragon: false,
                flail: false,
                garrote: false,
                ham: false,
                bladeH: false,
                bladeL: false,
                mace: false,
                pik: false,
                pole: false,
                sling: false,
                spear: false,
                staff: false,
                unarm: false,
                whip: false,
            },
            attackForm: "@profBonus+@enhance",
            attackFormImp: "@profImpBonus+@enhanceImp",
            damageForm: "@enhance",
            damageFormImp: "@enhanceImp",
            critDamageForm: "(@enhance)d6",
            critDamageFormImp: "(@enhanceImp)d6",
            critRange: 20,
            critRangeImp: 20,
            chatFlavor: "",
        },
        effects: [],
        folder: null,
        sort: 0,
        permission: {
            default: 0,
            "14Edqw6IS6HfTI0G": 3,
        },
        flags: {},
    };
}
class GenItem {
    data = {
        _id: "Ws0LMp0htIpvB8BL",
        name: "Neck",
        type: "equipment",
        img: "icons/equipment/neck/torc-ball-captive.webp",
        data: {
            description: { value: "", chat: "", unidentified: "" },
            source: "",
            quantity: 1,
            weight: 0,
            price: 0,
            attuned: true,
            equipped: true,
            rarity: "",
            identified: true,
            activation: { type: "", cost: 0, condition: "" },
            duration: { value: null, units: "" },
            target: { value: null, width: null, units: "", type: "" },
            range: { value: null, long: null, units: "" },
            uses: { value: 0, max: 0, per: "" },
            consume: { type: "", target: "", amount: null },
            armour: {
                value: 10,
                type: "",
                subType: "",
                ac: 0,
                fort: 0,
                ref: 0,
                wil: 0,
                dex: null,
                movePen: false,
                movePenValue: 0,
                skillCheck: false,
                skillCheckValue: 0,
                damageRes: { parts: [] },
            },
            hp: { value: 0, max: 0, dt: null, conditions: "" },
            macro: {
                type: "script",
                scope: "global",
                launchOrder: "off",
                command: "",
                author: "",
            },
            speed: { value: null, conditions: "" },
            strength: 0,
            stealth: false,
            proficient: true,
        },
        effects: [],
        folder: null,
        sort: 0,
        permission: { default: 0, "14Edqw6IS6HfTI0G": 3 },
        flags: {},
    };
}
class Implement {
    data = {
        _id: "",
        name: "",
        type: "weapon",
        img: "icons/weapons/staves/staff-ornate-orb-steel-red.webp",
        data: {
            description: {
                value: "",
                chat: "",
                unidentified: "",
            },
            source: "",
            quantity: 1,
            weight: 0,
            price: 0,
            attuned: false,
            equipped: true,
            rarity: "",
            identified: true,
            activation: {
                type: "",
                cost: 0,
                condition: "",
            },
            duration: {
                value: null,
                units: "",
            },
            target: {
                value: null,
                width: null,
                units: "",
                type: "",
            },
            range: {
                value: 0,
                long: 0,
                units: "",
            },
            uses: {
                value: 0,
                max: 0,
                per: "",
            },
            consume: {
                type: "",
                target: "",
                amount: null,
            },
            armour: {
                value: 10,
            },
            hp: {
                value: 0,
                max: 0,
                dt: null,
                conditions: "",
            },
            macro: {
                type: "script",
                scope: "global",
                launchOrder: "off",
                command: "",
                author: "",
            },
            level: "",
            weaponType: "implement",
            weaponHand: "hMain",
            properties: {
                amm: false,
                bru: false,
                def: false,
                hic: false,
                imp: true,
                lof: false,
                lom: false,
                off: false,
                rch: false,
                rel: false,
                sml: false,
                spc: false,
                thv: false,
                tlg: false,
                two: false,
                ver: false,
            },
            proficient: true,
            proficientI: true,
            profBonus: 0,
            profImpBonus: 0,
            enhance: 1,
            isRanged: false,
            damageDice: {
                parts: [],
            },
            damage: {
                parts: [],
                versatile: "",
            },
            damageCrit: {
                parts: [],
                versatile: "",
            },
            damageImp: {
                parts: [],
                versatile: "",
            },
            damageCritImp: {
                parts: [],
                versatile: "",
            },
            damageType: {
                physical: false,
                damage: true,
                acid: false,
                cold: false,
                fire: false,
                force: false,
                lightning: false,
                necrotic: false,
                poison: false,
                psychic: false,
                radiant: false,
                thunder: false,
            },
            brutalNum: 1,
            weaponGroup: {
                axe: false,
                bow: false,
                cbow: false,
                flail: false,
                ham: false,
                bladeH: false,
                bladeL: false,
                mace: false,
                pik: false,
                pole: false,
                sling: false,
                spear: false,
                staff: false,
                unarm: false,
            },
            attackForm: "@profBonus+@enhance",
            attackFormImp: "@profImpBonus+@enhanceImp",
            damageForm: "@enhance",
            damageFormImp: "@enhanceImp",
            critDamageForm: "(@enhance)d6",
            critDamageFormImp: "(@enhanceImp)d6",
            critRange: 20,
            critRangeImp: 20,
            ability: null,
            actionType: null,
            attackBonus: 0,
            chatFlavor: "",
            critical: null,
            formula: "",
            save: {
                ability: "",
                dc: null,
                scaling: "spell",
            },
        },
        effects: [],
        folder: null,
        sort: 0,
        permission: {
            "14Edqw6IS6HfTI0G": 3,
        },
        flags: {
            core: {
                sourceId: "Item.uYqp8trQKVyjhFFl",
            },
        },
    };
}

export { Power, Feat, Armour, Weapon, GenItem, Implement };
